"""Domain model representing a single conversational turn (Checkpoint 6)."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Literal

SpeakerRole = Literal["human", "bot"]
InputType = Literal["voice", "text"]


@dataclass(frozen=True)
class ConversationTurn:
    """Represents a single conversational turn in the voice room.

    Attributes:
        speaker_id: Unique participant identity (e.g. 'human-abc123', 'ai-dost', 'ai-sathi').
        speaker_name: Display name of the participant (e.g. 'Manash', 'AI Dost', 'AI Sathi').
        role: Entity role ('human' or 'bot').
        text: Normalized transcript or chat text of the turn.
        input_type: Interaction modality ('voice' or 'text').
        target_bot: Targeted bot if explicitly addressed or routed ('dost', 'sathi', or None).
        timestamp: UTC timestamp when the turn occurred.
    """

    speaker_id: str
    speaker_name: str
    role: SpeakerRole
    text: str
    input_type: InputType = "voice"
    target_bot: str | None = None
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))

    @property
    def is_human(self) -> bool:
        """True if the turn was uttered or typed by a human participant."""
        return self.role == "human"

    @property
    def is_bot(self) -> bool:
        """True if the turn was generated by an AI assistant."""
        return self.role == "bot"

    def format_line(self) -> str:
        """Format the turn as a clean line for LLM context injection."""
        modality = f" ({self.input_type})" if self.input_type else ""
        return f'- {self.speaker_name}{modality}: "{self.text}"'
